config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # read all
  get 'tasks', to: 'tasks#index', as: :tasks

  # create one
  get 'tasks/new', to: 'tasks#new'
  post 'tasks', to: 'tasks#create'

  # read one - show must go after the "new" routes
  get 'tasks/:id', to: 'tasks#show', as: :task

  # edit one
  get 'tasks/:id/edit', to: 'tasks#edit', as: :edit_task
  patch 'tasks/:id', to: 'tasks#update'

  # delete one
  delete 'tasks/:id', to: 'tasks#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  def index
    @tasks = Task.all
  end

  def show
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to task_path(@task)
  end

  def edit
  end

  def update
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy
    @task.destroy
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end

  def set_task
    @task = Task.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskManagerRailsApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= simple_form_for(@task) do |f| %>
  <%= f.input :title %>
  <%= f.input :details %>
  <% unless f.object.new_record? %>
    <div class="checkbox">
      <label>
        <%= f.check_box :completed %> Completed
      </label>
    </div>
  <% end %>
  <%= f.button :submit, class: 'btn btn-outline-info' %>
<% end %>

app/views/tasks/edit.html.erb
<div class="container">
  <h1 class="my-3 font-weight-bolder text-info">Edit Task</h1>
  <%= render "form", task: @task %>
  <%= link_to 'Back to list', tasks_path, :class => "btn btn-outline-info" %>
</div>

app/views/tasks/index.html.erb
<div class="container">
  <h1 class="my-3 font-weight-bolder text-info">My Tasks</h1>
  <% @tasks.each do |task| %>
    <p class="mb-0 text-secondary">
      <% if task.completed == true %>
        <i class="far fa-check-square"></i>
      <% else %>
        <i class="far fa-square"></i>
      <% end %>
      <%= link_to task.title.capitalize, task_path(task) %>
      <%= link_to task_path(task), method: :delete, data: { confirm: "Are you sure?" } do %>
        <i class="far fa-trash-alt"></i>
      <% end %>
    </p>
  <% end %>
  <div class="container border border-secondary my-3"></div>
  <%= link_to tasks_new_path do %>
    <i class="fas fa-plus"></i> Add a new task
  <% end %>
  <!-- another option to insert the icon into the rails link -->
  <!-- <%= link_to '<i class="fas fa-plus"></i> Add a new task'.html_safe, tasks_new_path %> -->
</div>

app/views/tasks/new.html.erb
<div class="container">
  <h1 class="my-3 font-weight-bolder text-info">New Task</h1>
  <%= render "form", task: @task %>
  <%= link_to 'Back to list', tasks_path, :class => "btn btn-outline-info" %>
</div>

app/views/tasks/show.html.erb
<div class="container">
  <div class="d-flex justify-content-between align-items-center">
    <h1 class="my-3 font-weight-bolder text-info"><%= @task.title.capitalize %></h1>
    <%= link_to edit_task_path(@task), :class => "btn btn-secondary" do %>
      <i class="far fa-edit"></i> Edit this task
    <% end %>
  </div>
  <p class="mb-0 text-secondary py-3 px-2 bg-light border border-secondary rounded"><%= @task.details %></p>
  <p class="mb-0 py-3 text-secondary">
    <% if @task.completed == true %>
      <i class="far fa-check-square"></i> This task is completed!
    <% else %>
      <i class="far fa-square"></i> This task is not completed yet!
    <% end %>
  </p>
  <%= link_to 'Back to list', tasks_path %>
</div>